subdir-ccflags-y := \
    -fdata-sections -ffunction-sections -finline-functions -ftree-vectorize -funroll-loops

goodixfp_gf5228_drv_tee-objs := gf_spi.o platform.o netlink.o
obj-$(CONFIG_GOODIX_GF5228)	+= goodixfp_gf5228_drv_tee.o
